// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';

const capacitorStorage = {
  getItem: async (key: string) => {
    const { value } = await Preferences.get({ key });
    return value;
  },
  setItem: async (key: string, value: string) => {
    await Preferences.set({ key, value });
  },
  removeItem: async (key: string) => {
    await Preferences.remove({ key });
  }
};


const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be set.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: Capacitor.isNativePlatform() ? capacitorStorage : brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // PKCE avoids exposing tokens in URL fragments (safer on shared POS terminals)
    flowType: 'pkce',
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'zenpos-web',
    },
  },
});


// ==========================================
// OFFLINE-FIRST MUTATION INTERCEPTOR
// ==========================================


const originalFrom = supabase.from.bind(supabase);

// Create a dummy builder that absorbs chained calls (.select, .single, .eq, etc)
// and eventually resolves to a fake successful response
const createOfflineDummyBuilder = (mockData: any) => {
  const dummy: any = Promise.resolve({ data: mockData, error: null });
  const chainableMethods = ['select', 'single', 'eq', 'in', 'order', 'limit', 'match', 'or', 'contains'];
  
  chainableMethods.forEach(method => {
    dummy[method] = () => dummy;
  });
  
  return dummy;
};

(supabase as any).from = (table: string) => {
  const builder = originalFrom(table);
  
  const originalInsert = builder.insert.bind(builder);
  const originalUpdate = builder.update.bind(builder);
  const originalDelete = builder.delete.bind(builder);

  builder.insert = (payload: any, options?: any) => {
    const isLocalOnly = localStorage.getItem('privacy_storage_mode') === 'local';
    if (!navigator.onLine || isLocalOnly) {
      import('@/utils/offlineManager').then(({ offlineManager }) => {
        // Ensure payload is array for iteration
        const payloads = Array.isArray(payload) ? payload : [payload];
        payloads.forEach(p => {
          if (!p.id) p.id = crypto.randomUUID(); // Auto-generate ID if missing
          offlineManager.queueWrite({
            table,
            operation: 'INSERT',
            data: p
          });
        });
      });
      return createOfflineDummyBuilder(Array.isArray(payload) ? payload : [payload]);
    }
    return originalInsert(payload, options);
  };

  builder.update = (payload: any, options?: any) => {
    const isLocalOnly = localStorage.getItem('privacy_storage_mode') === 'local';
    if (!navigator.onLine || isLocalOnly) {
      // For updates, we need the ID, but it's usually chained like .update(p).eq('id', id)
      // We can capture the 'eq' call!
      const dummy = createOfflineDummyBuilder(payload);
      const originalEq = dummy.eq;
      dummy.eq = (column: string, value: any) => {
        if (column === 'id') {
          payload.id = value;
          import('@/utils/offlineManager').then(({ offlineManager }) => {
            offlineManager.queueWrite({
              table,
              operation: 'UPDATE',
              data: payload
            });
          });
        }
        return dummy;
      };
      
      // Also capture .in for bulk updates
      dummy.in = (column: string, values: any[]) => {
         if (column === 'id') {
           import('@/utils/offlineManager').then(({ offlineManager }) => {
             values.forEach(val => {
               offlineManager.queueWrite({
                 table,
                 operation: 'UPDATE',
                 data: { ...payload, id: val }
               });
             });
           });
         }
         return dummy;
      };

      return dummy;
    }
    return originalUpdate(payload, options);
  };

  builder.delete = (options?: any) => {
    const isLocalOnly = localStorage.getItem('privacy_storage_mode') === 'local';
    if (!navigator.onLine || isLocalOnly) {
      const dummy = createOfflineDummyBuilder(null);
      dummy.eq = (column: string, value: any) => {
        if (column === 'id') {
          import('@/utils/offlineManager').then(({ offlineManager }) => {
            offlineManager.queueWrite({ table, operation: 'DELETE', data: { id: value } });
          });
        }
        return dummy;
      };
      dummy.in = (column: string, values: any[]) => {
         if (column === 'id') {
           import('@/utils/offlineManager').then(({ offlineManager }) => {
             values.forEach(val => {
               offlineManager.queueWrite({ table, operation: 'DELETE', data: { id: val } });
             });
           });
         }
         return dummy;
      };
      return dummy;
    }
    return originalDelete(options);
  };

  return builder;
};
